# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app


# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Expose port 5003 for the Flask service
EXPOSE 5005

# Run read-service.py when the container launches
CMD ["python", "message-service.py"]

